name: Run Telegram Shill Bot

on:
  schedule:
    - cron: '0 */2 * * *'  # Elke 2 uur
  workflow_dispatch:

jobs:
  run-shill-bot:
    runs-on: ubuntu-latest
    concurrency:
      group: telegram-shill-bot
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy .env from secrets
        run: |
          echo "API_ID=${{ secrets.API_ID }}" >> .env
          echo "API_HASH=${{ secrets.API_HASH }}" >> .env
          echo "SESSION_STRING=${{ secrets.SESSION_STRING }}" >> .env
          echo "REMOTE_API_URL=${{ secrets.REMOTE_API_URL }}" >> .env

      - name: Run shill bot
        run: python shill_bot.py